### ISSUE TITLE
MCM will not show up at all

### ISSUE THREAD

**Issue by CarlW1960** [garryrot/telekinesis#1]
Hello,
I can't get the MCM to even show up in my game. I am playing the recent SE version 1.6130 ? I am using MO2 and installed the Telekinesis mod 1.3 . I ran FNIS just in case. NOTHING SHOW US . HELP.

**Comment by garryrot** [comment]
Hey, thank you for reporting this. I fixed this issue with 1.3.1 https://github.com/garryrot/telekinesis/releases/tag/1.3.1
