### ISSUE TITLE
Adding Milk Mod Economy

### ISSUE THREAD

**Issue by sylphia-nox** [garryrot/telekinesis#2]
Hello!  Wanted to start by saying I've been enjoying this mod but was disapointed to find out it doesn't support Milk Mod Economy.  I tried to spend time today to see if I could get it working myself but just ran into issue after issue trying to get things setup.  CMake just refused to work and other things just failed as well.  I did end up managing to figure out what events should be used for the listeners and prototype up the below taking advantage of the existing devious devices setup.  Anyway, would love to see this get added but would very much understand if it is not something you want to put the effort in.  I wish I could be doing this as a PR but its just not working out that way (unless you would like me to go ahead and try to do that without being able to test it.)

Thank you!

```
;               __  ____ ____      __  ___          __   ______                                      
;              /  |/  (_) / /__   /  |/  /___  ____/ /  / ____/________  ____  ____  ____ ___  __  __
;             / /|_/ / / / //_/  / /|_/ / __ \/ __  /  / __/ / ___/ __ \/ __ \/ __ \/ __ `__ \/ / / /
;            / /  / / / / ,<    / /  / / /_/ / /_/ /  / /___/ /__/ /_/ / / / / /_/ / / / / / / /_/ / 
;           /_/  /_/_/_/_/|_|  /_/  /_/\____/\__,_/  /_____/\___/\____/_/ /_/\____/_/ /_/ /_/\__, /  
;                                                                                           /____/   


Function InitMilkModHandlers()
        RegisterForModEvent("MilkQuest.StartMilkingMachine", "OnMilkModVibrateEffectStart")
	RegisterForModEvent("MilkQuest.StopMilkingMachine",  "OnVibrateEffectStop")
		
	RegisterForModEvent("MilkQuest.FeedingStage", "OnMilkModVibrateEffectStart")
	RegisterForModEvent("MilkQuest.MilkingStage",  "OnMilkModVibrateEffectStart")
	RegisterForModEvent("MilkQuest.FuckMachineStage", "OnMilkModVibrateEffectStart")
EndFunction

Bool _MilkMod_Vibrate = false
Bool Property MilkMod_Vibrate Hidden
    Function Set(Bool enable)
        _MilkMod_Vibrate = enable
    EndFunction
    Bool Function Get()
        return _MilkMods_Vibrate
    EndFunction
EndProperty

Event OnMilkModVibrateEffectStart(String eventName, String actorName, Float vibrationStrength, Form sender)
    If !_DeviousDevices_Vibrate || ZadLib == None
        return
    EndIf

    If PlayerRef.GetLeveledActorBase().GetName() != actorName
        return ; Not the player
    EndIf

    String[] events = new String[3]
    Float numVibratorsMult = 0
    If eventName == "MilkQuest.FeedingStage"
        numVibratorsMult = 0.3
        events[1] = DeviousDevices_Vibrate_Event_Anal
    EndIf
    If eventName == "MilkQuest.MilkingStage"
        numVibratorsMult = 0.55
        events[1] = DeviousDevices_Vibrate_Event_Anal
        events[2] = DeviousDevices_Vibrate_Event_Nipple
    EndIf
    If eventName == "MilkQuest.FuckMachineStage"
        numVibratorsMult = 0.95
        events[1] = DeviousDevices_Vibrate_Event_Anal
        events[0] = DeviousDevices_Vibrate_Event_Vaginal
    EndIf
    If eventName == "MilkQuest.StartMilkingMachine"
        numVibratorsMult = 1.25
        events[0] = DeviousDevices_Vibrate_Event_Vaginal
        events[1] = DeviousDevices_Vibrate_Event_Anal
        events[2] = DeviousDevices_Vibrate_Event_Nipple
    EndIf

    Int strength = Math.Floor((vibrationStrength / numVibratorsMult) * 20)
    TDevices.StopHandle(_DeviousDevicesVibrateHandle)
    _DeviousDevicesVibrateHandle = StartVibration(DeviousDevices_Vibrate_DeviceSelector, -1, DeviousDevices_Vibrate_Pattern, DeviousDevices_Vibrate_Funscript, strength, events)
EndEvent
```

**Comment by garryrot** [comment]
Hey, very cool Idea, I didn't think of that mod.

A few things:
- There is no need to use CMake etc to extend this mod you mainly need to do that only for the native library, which I assume you don't want to change / rebuild.
- You can build your own esp, make it depend on Telekinesis.esp, fetch the main quest (like I do [here](https://github.com/garryrot/telekinesis/blob/master/contrib/Distribution/Source/Scripts/Tele_OnGameLoadObserver.psc) with other mods) [Tele_Devices.psc](https://github.com/garryrot/telekinesis/blob/master/contrib/Distribution/Source/Scripts/Tele_Devices.psc), and just start using the methods exposed by that method. But if you do, please tell me so that I stop changing the API (lol).

There are a few problems with your code and I won't be able to merge that:

- StartVibration is an internal helper method I utilize to access some common MCM settings for vibrations. You are using the Devious Devices Settings, but you would need to create your own set of settings in the MCM for Milk Mod Economy, or you use TDevices.Vibrate directly.
- You overwrite the _DeviousDevicesVibrateHandle that is used to track currently running DD vibration tasks, which could result in them not stopping cause it lost the handle.

- I would be interested in adding that at some point, and your code is helpful to see how it could be done.
- I don't know when / how I would include it (too much to do)
- Right now I'm also working on a separate project that would allow you to define such things by json configuration, i.e. mapping in-game events to specific device actions.

**Comment by garryrot** [comment]
> Hello! Wanted to start by saying I've been enjoying this mod but was disapointed to find out it doesn't support Milk Mod Economy. I tried to spend time today to see if I could get it working myself but just ran into issue after issue trying to get things setup. CMake just refused to work and other things just failed as well. I did end up managing to figure out what events should be used for the listeners and prototype up the below taking advantage of the existing devious devices setup. Anyway, would love to see this get added but would very much understand if it is not something you want to put the effort in. I wish I could be doing this as a PR but its just not working out that way (unless you would like me to go ahead and try to do that without being able to test it.)

Can you elaborate on what you have to do to get those events to trigger in Milk Mod Economy?

I tried using the milk machine with my PC, nothing happens. 

I tried to drink the lactaid and become a milk maid, and nothing happens again.

**Comment by sylphia-nox** [comment]
I actually got it fully working myself and I've been meaning to PR it back
in but have not gotten to that yet.  I think I'll try to do that today.

The events should trigger when using the milk machine.  The version I have
is working.

**Comment by garryrot** [comment]
> I actually got it fully working myself and I've been meaning to PR it back in but have not gotten to that yet. I think I'll try to do that today. The events should trigger when using the milk machine. The version I have is working.
> […](#)

Do you run the SE version from LL? https://www.loverslab.com/files/file/6103-milk-mod-economy-se/

Milk-Mod-Economy-Scripts-20220522.7z

**Comment by sylphia-nox** [comment]
That looks right.  I just got the PR up if you want to take a look at how I implemented it.  I tried to copy your existing setup for things.

**Comment by garryrot** [comment]
> That looks right. I just got the PR up if you want to take a look at how I implemented it. I tried to copy your existing setup for things.

Yeah I figured the event issue, it was skill issue (on my part). 

I'm currently working on a project to hook to events with a generic json configuration ( [see here if interested](https://github.com/garryrot/lovebug/blob/master/deploy/Data/SKSE/Plugins/Lovebug/triggers/MilkMod.json) ), but unfortunately that seems to just not work for events that are non-standard parametrized.

I want to have a more generalized solution, to save everyone all of the trouble you had to go through, but that also ate my time and kept me from implementing new features.

**Comment by garryrot** [comment]
Solved by merging https://github.com/garryrot/telekinesis/pull/4
