### ISSUE TITLE
MCM device menu broken on master branch

### ISSUE THREAD

**Issue by sylphia-nox** [garryrot/telekinesis#3]
Was working on a build off of master and ran into this bug.  Spent a lot of time trying to fix since it was only happening on my version of 
Tele_MCM.  After switching off of master and onto 1.3.1, the bug dissapeared, so it looks like the recent PR merge actually broke some things.  I am unsure if it is a niche bug or if it would be more widespread.  In case the screenshot is clear, most of the mcm menu options for devices are missing.

![The Elder Scrolls V  Skyrim Special Edition Screenshot 2024 03 04 - 16 12 47 85](https://github.com/garryrot/telekinesis/assets/19786970/a9535088-acfb-4bfd-813d-27ea5fa0f749)

**Comment by garryrot** [comment]
So to get this right, did you use one of the packaged versions, or did you compile yourself?

**Comment by garryrot** [comment]
Yup I think I can reproduce it. The issue occurs since 1.3.3 when you have a new device (that was previously not part of Telekinesis.json).

It simply fails to detect the actuator type cause I made an oopsie.

**Comment by garryrot** [comment]
I will fix this very soon (tomorrow)

**Comment by garryrot** [comment]
This should fix it, can you test it? I'm not going to release it instantly right now, until I've testet it to prevent another oopsie

[Telekinesis.1.3.4-rc1.zip](https://github.com/garryrot/telekinesis/files/14489188/Telekinesis.1.3.4-rc1.zip)

**Comment by garryrot** [comment]
So the fix seems to work, I released it as 1.3.4, the fix seems to be something that shouldn't have any other negative effects (famous last words)
