### ISSUE TITLE
Telekinesis never loads into the MCM:  Tried with existing game and new game

### ISSUE THREAD

**Issue by DarkKaplah** [garryrot/telekinesis#5]
Trying to load this up but Telekinesis never loads.  I've tried on a new game and existing save.  Just never comes up in the game.  I'm on AE and am using Vortex.  Just learned of this project and installed it yesterday so perhaps a Skyrim update broke it?
[Papyrus.0.log](https://github.com/garryrot/telekinesis/files/15112344/Papyrus.0.log)

**Comment by garryrot** [comment]
- Which version do you run? (Game + Telekinesis)

- You have A LOT of errors in your log, 80.000 lines of papyrus log just for start up is a lot. Is that happening without Tele?

- Is that papyrus log of the your first start with Telekinesis.esp loaded?

**Comment by DarkKaplah** [comment]
Sorry for the delay.  

- Game Version 1.6.1170.0.8 (SKSE64 2.2.6 rel     <- Skyrim Anniversary Edition
- Yes.  I've found saves keep building up errors.  I've cleared out the errors with a save tool and Tele still won't load.  I've also started a new character and same problem.
- Not sure what you're asking for here.  I can tell you the new character I created also doesn't load Telekinesis.  The ESP is activated in vortex, but it never shows up in the MCM.
- Of everything you have listed I don't have OStim.esp.  It was listed in your comments as optional so I left it off.  Otherwise I'm including my load order here.  
- I am seeing lots of warnings related to Bathing Beauties.  However this has always worked even with the warnings.
- I am seeing "Tele" errors early in the papyrus log.  It is reporting missing files.  I'm wondering if I either improperly downloaded this from github, or if tele isn't compatible with Skyrim AE.  I know SE/AE broke some of my favorite followers.
[Plugins.txt](https://github.com/garryrot/telekinesis/files/15222536/Plugins.txt)
[Papyrus.0.log](https://github.com/garryrot/telekinesis/files/15222616/Papyrus.0.log)

**Comment by garryrot** [comment]
> Sorry for the delay.
> 
> * Game Version 1.6.1170.0.8 (SKSE64 2.2.6 rel     <- Skyrim Anniversary Edition.
> * Not sure what you're asking for here.  I can tell you the new character I created also doesn't load Telekinesis.  The ESP is activated in vortex, but it never shows up in the MCM.
> * Of everything you have listed I don't have OStim.esp.  It was listed in your comments as optional so I left it off.  Otherwise I'm including my load order here.

There used to be a bug in Telekinesis version 1.3.x (and earlier) that caused the MCM to not load if Ostim.esp was missing. It is an optional dependency so this was not supposed to happen.

In the current version of Telekinesis this should be fixed, thats why I'm asking for the verison of the mod that you use.

Edit: I just testet Telekinesis 1.4.1 it with no dependencies at all (just SkyUI) and it should definitely work now.

**Comment by garryrot** [comment]
You might also want to check your skse64.log if telekinesis.dll actually loads

**Comment by DarkKaplah** [comment]
I just grabbed it from your git a day before the first post.  It should be 1.4.1.  Now I grabbed this by doing a "Download zip" on your code page, then zipping the "Deploy" folder as Telekinesis.7z, then adding it to Vortex.  I'm seeing Telekinesis.esp in my skse64.log.

[skse64.log](https://github.com/garryrot/telekinesis/files/15239750/skse64.log)

**Comment by garryrot** [comment]
> I just grabbed it from your git a day before the first post. It should be 1.4.1. Now I grabbed this by doing a "Download zip" on your code page, then zipping the "Deploy" folder as Telekinesis.7z, then adding it to Vortex. I'm seeing Telekinesis.esp in my skse64.log.
> 
> [skse64.log](https://github.com/garryrot/telekinesis/files/15239750/skse64.log)

Oh I see. Thats not how you install the mod.

You need to download the actual release `Telekinesis.1.4.1.7z` from the "releases" page.

![Release0](https://github.com/garryrot/telekinesis/assets/121590509/2073c823-5772-4fd1-94e5-fcf83deb111d)
![Release1](https://github.com/garryrot/telekinesis/assets/121590509/627d70f6-4b30-40ee-9596-c962afe3db50)

Github is a page to host version control for software development. What you originally downloaded was a mirror of the source code. What you actually need is a compiled version of the software, i.e. the 7z that is hosted on Loverslab or on the Release tab.

**Comment by garryrot** [comment]
I'm going to assume that this issue is resolved, feel free to comment if it still doesn'T work.

**Comment by DarkKaplah** [comment]
That was it!  Definitely a "PEBKAC" error.  My fault fully.  Thank you for your patience and assistance.
