### ISSUE TITLE
is this only for bluetooth toys?

### ISSUE THREAD

**Issue by deathtome1998** [garryrot/telekinesis#7]
as the title says, I was wondering if this only works with Bluetooth toys? I'm getting an SR6 from tempest max's patreon to build soon, but as far as I know it doesn't have Bluetooth. I hope it works since it's a stroker which is the only thing I'd use on here. can someone let me know if it does?

**Comment by garryrot** [comment]
It supports anything that the Intiface app (or https://github.com/buttplugio/buttplug) can do, but not necessarily in-process, so you might have to use the Intiface app and use a websocket connector for certain devices.

For help on device support you can check out the [buttplug.io docs](https://buttplug.io/) and their [discord](https://discord.gg/2Dxj5W4T), I think it is possible to use certain devices from that manufacturer, but there seems to be some configuration required.
